[package]
name = "cuda-artifact-finalizer"
version = "0.2.1"
edition.workspace = true
description = "Driver-independent NVVM IR and LTOIR finalization for cuda-oxide"
readme = "README.md"
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
llvm-nvptx = ["dep:libloading"]

[dependencies]
libnvvm-sys = { workspace = true }
nvjitlink-sys = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
libloading = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true }
